#!/usr/bin/env python # -*- coding: UTF-8 -*-
# Main.py
import cgi

import cv2
import numpy as np

print "Content-Type: text/html asd" 
print ""
print "<html>"
print "<h2>CGI Script Output</h2>"
print "<p>This page was generated by a Python CGI script.</p>"
print "</html>"
